-- Canonical knowledge schema, authored from the empty v2 table inventory.
-- This migration is static; runtime never translates SQLite statements.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE events(id TEXT PRIMARY KEY, session TEXT, turn TEXT, kind TEXT, project TEXT,
          payload TEXT, created DOUBLE PRECISION, processed INTEGER DEFAULT 0);

CREATE TABLE memories(id TEXT PRIMARY KEY, session TEXT, project TEXT, body TEXT, kind TEXT,
          created DOUBLE PRECISION, active INTEGER DEFAULT 1, command_key TEXT, exit_code INTEGER, turn TEXT DEFAULT '', environment_key TEXT);

CREATE TABLE memory_fts(id TEXT NOT NULL,body TEXT NOT NULL);

CREATE TABLE offers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session TEXT, turn TEXT, memory_id TEXT,
          created DOUBLE PRECISION, delivery TEXT DEFAULT 'offered', UNIQUE(session,turn,memory_id));

CREATE TABLE outcomes(id TEXT PRIMARY KEY, memory_id TEXT, event_id TEXT,
          classification TEXT, created DOUBLE PRECISION);

CREATE TABLE outbox(id TEXT PRIMARY KEY, payload TEXT, status TEXT DEFAULT 'pending',
          attempts INTEGER DEFAULT 0, last_error TEXT, response TEXT, next_attempt DOUBLE PRECISION DEFAULT 0);

CREATE TABLE historical_sources(source_id TEXT, correction_id TEXT,
          PRIMARY KEY(source_id,correction_id));

CREATE TABLE counters(key TEXT PRIMARY KEY,value INTEGER NOT NULL);

CREATE TABLE memory_feedback(memory_id TEXT PRIMARY KEY,
          result TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);

CREATE TABLE memory_exclusions(memory_id TEXT PRIMARY KEY,
          source_id TEXT NOT NULL, reason TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);

CREATE TABLE memory_access(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, memory_id TEXT,
          revision TEXT, project TEXT, session TEXT, channel TEXT, characters INTEGER, created DOUBLE PRECISION);

CREATE TABLE health(key TEXT PRIMARY KEY, value TEXT);

CREATE TABLE source_event_metadata(
          source_id TEXT PRIMARY KEY, tool_name TEXT NOT NULL, source_role TEXT NOT NULL,
          capture_id TEXT, event_fields TEXT NOT NULL, response_shape TEXT NOT NULL,
          created DOUBLE PRECISION NOT NULL);

CREATE TABLE remote_offers(id TEXT PRIMARY KEY, session TEXT, turn TEXT, record_id TEXT,
          command_key TEXT, created DOUBLE PRECISION, reported INTEGER DEFAULT 0, environment_key TEXT, UNIQUE(session,turn,record_id));

CREATE TABLE observer_jobs(id TEXT PRIMARY KEY, project TEXT, session TEXT,
      source_ids TEXT, status TEXT DEFAULT 'pending', attempts INTEGER DEFAULT 0,
      next_attempt DOUBLE PRECISION DEFAULT 0, created DOUBLE PRECISION, error TEXT, usage TEXT, model TEXT, version TEXT);

CREATE TABLE observer_seen(source_id TEXT PRIMARY KEY, job_id TEXT);

CREATE TABLE observation_sources(memory_id TEXT, source_id TEXT,
      PRIMARY KEY(memory_id,source_id));

CREATE TABLE memory_reviews(memory_id TEXT PRIMARY KEY, decision TEXT,
      categories TEXT, draft_title TEXT, draft_evidence TEXT, model TEXT, version TEXT);

CREATE TABLE contribution_reviews(id TEXT PRIMARY KEY, payload TEXT,
      source_ids TEXT, status TEXT DEFAULT 'pending', decision TEXT, attempts INTEGER DEFAULT 0,
      next_attempt DOUBLE PRECISION DEFAULT 0, created DOUBLE PRECISION, error TEXT, reviewed_hash TEXT, model TEXT, version TEXT);

CREATE TABLE observer_progress(job_id TEXT PRIMARY KEY, observations TEXT, reviews TEXT DEFAULT '{}', selection_decisions TEXT DEFAULT '[]');

CREATE TABLE model_calls(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created DOUBLE PRECISION, purpose TEXT,
      model TEXT, status TEXT, usage TEXT);

CREATE TABLE memory_outcome_support(memory_id TEXT PRIMARY KEY,
      version TEXT, assessment TEXT, created DOUBLE PRECISION);

CREATE TABLE model_call_details(call_id INTEGER PRIMARY KEY,
        attempt_id TEXT, job_kind TEXT, job_id TEXT, project TEXT, session TEXT,
        source_sessions TEXT, finished DOUBLE PRECISION, elapsed_seconds DOUBLE PRECISION);

CREATE TABLE memory_metadata(
      memory_id TEXT PRIMARY KEY, schema_version INTEGER NOT NULL, domain TEXT NOT NULL,
      knowledge_type TEXT NOT NULL, subjects TEXT NOT NULL, tags TEXT NOT NULL,
      applicability_text TEXT NOT NULL, applicability_constraints TEXT NOT NULL,
      evidence_status TEXT NOT NULL, decision_reason TEXT NOT NULL,
      source_segment_ids TEXT NOT NULL, updated DOUBLE PRECISION NOT NULL);

CREATE TABLE curation_decisions(
      id TEXT PRIMARY KEY, job_id TEXT NOT NULL, source_id TEXT NOT NULL,
      segment_id TEXT NOT NULL, decision TEXT NOT NULL, reason TEXT NOT NULL,
      version TEXT NOT NULL, created DOUBLE PRECISION NOT NULL,
      UNIQUE(source_id,segment_id,version));

CREATE INDEX curation_decisions_source ON curation_decisions(source_id);

CREATE TABLE memory_candidates(
        id TEXT PRIMARY KEY, project TEXT, request_key TEXT, request_hash TEXT,
        title TEXT, evidence TEXT, source_ids TEXT, replaces TEXT,
        status TEXT DEFAULT 'pending', decision TEXT, attempts INTEGER DEFAULT 0,
        next_attempt DOUBLE PRECISION DEFAULT 0, created DOUBLE PRECISION, error TEXT, replacement_ids TEXT DEFAULT '[]',
        UNIQUE(project,request_key));

CREATE TABLE knowledge_documents(
      document_id TEXT PRIMARY KEY, project TEXT NOT NULL, owner_session TEXT,
      origin_memory_id TEXT NOT NULL UNIQUE, lifecycle TEXT NOT NULL,
      active_revision_id TEXT, schema_version INTEGER NOT NULL,
      created DOUBLE PRECISION NOT NULL, updated DOUBLE PRECISION NOT NULL);

CREATE INDEX knowledge_documents_active ON knowledge_documents(project,lifecycle);

CREATE TABLE knowledge_document_members(
      document_id TEXT NOT NULL, memory_id TEXT NOT NULL,
      relation TEXT NOT NULL, created DOUBLE PRECISION NOT NULL,
      PRIMARY KEY(document_id,memory_id));

CREATE INDEX knowledge_members_memory ON knowledge_document_members(memory_id);

CREATE TABLE knowledge_revisions(
      revision_id TEXT PRIMARY KEY, document_id TEXT NOT NULL,
      revision_number INTEGER NOT NULL, claim_json TEXT NOT NULL,
      identity_json TEXT NOT NULL, identity_hash TEXT NOT NULL,
      previous_revision_id TEXT, reason TEXT NOT NULL,
      schema_version INTEGER NOT NULL, created DOUBLE PRECISION NOT NULL,
      UNIQUE(document_id,revision_number));

CREATE INDEX knowledge_revisions_identity ON knowledge_revisions(identity_hash);

CREATE TABLE knowledge_fts(document_id TEXT NOT NULL,revision_id TEXT NOT NULL,body TEXT NOT NULL);

CREATE TABLE knowledge_index_rows(
      document_id TEXT PRIMARY KEY, revision_id TEXT NOT NULL);

CREATE TABLE knowledge_index_state(
      singleton INTEGER PRIMARY KEY CHECK(singleton=1), schema_version INTEGER NOT NULL);

CREATE TABLE knowledge_embeddings(
      model_key TEXT NOT NULL, document_id TEXT NOT NULL, revision_id TEXT NOT NULL,
      content_sha256 TEXT NOT NULL, dimension INTEGER NOT NULL, vector BYTEA NOT NULL,
      created DOUBLE PRECISION NOT NULL, PRIMARY KEY(model_key,document_id));

CREATE INDEX knowledge_embeddings_revision
      ON knowledge_embeddings(model_key,revision_id);

CREATE TABLE knowledge_embedding_state(
      model_key TEXT PRIMARY KEY, schema_version INTEGER NOT NULL,
      dimension INTEGER NOT NULL, status TEXT NOT NULL,
      completed DOUBLE PRECISION, updated DOUBLE PRECISION NOT NULL);

CREATE TABLE knowledge_embedding_build(
      model_key TEXT PRIMARY KEY, schema_version INTEGER NOT NULL,
      dimension INTEGER NOT NULL, last_document_id TEXT NOT NULL,
      started DOUBLE PRECISION NOT NULL);

CREATE TABLE knowledge_search_shadow_comparisons(
      id TEXT PRIMARY KEY, project TEXT NOT NULL, query_hash TEXT NOT NULL,
      lexical_json TEXT NOT NULL, hybrid_json TEXT NOT NULL,
      model_key TEXT, fallback_reason TEXT, created DOUBLE PRECISION NOT NULL);

CREATE INDEX knowledge_search_shadow_created
      ON knowledge_search_shadow_comparisons(created);

CREATE TABLE knowledge_support(
      revision_id TEXT NOT NULL, source_memory_id TEXT NOT NULL,
      source_segment_id TEXT, relation TEXT NOT NULL,
      independence TEXT NOT NULL, created DOUBLE PRECISION NOT NULL,
      UNIQUE NULLS NOT DISTINCT(revision_id,source_memory_id,source_segment_id,relation));

CREATE INDEX knowledge_support_source ON knowledge_support(source_memory_id);

CREATE TABLE knowledge_relations(
      id TEXT PRIMARY KEY, document_id TEXT NOT NULL, related_document_id TEXT NOT NULL,
      relation TEXT NOT NULL, score DOUBLE PRECISION, reason TEXT NOT NULL,
      algorithm_version TEXT NOT NULL, review_state TEXT NOT NULL, created DOUBLE PRECISION NOT NULL,
      UNIQUE(document_id,related_document_id,relation,algorithm_version));

CREATE TABLE consolidation_decisions(
      id TEXT PRIMARY KEY, action TEXT NOT NULL, input_revision_ids TEXT NOT NULL,
      output_document_id TEXT, algorithm_version TEXT NOT NULL,
      reason TEXT NOT NULL, review_state TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);

CREATE TABLE knowledge_index_build(
      singleton INTEGER PRIMARY KEY CHECK(singleton=1), schema_version INTEGER NOT NULL,
      last_document_id TEXT NOT NULL, started DOUBLE PRECISION NOT NULL);

CREATE TABLE knowledge_shadow_comparisons(
      id TEXT PRIMARY KEY,project TEXT NOT NULL,session_hash TEXT NOT NULL,query_hash TEXT NOT NULL,
      legacy_json TEXT NOT NULL,knowledge_json TEXT NOT NULL,created DOUBLE PRECISION NOT NULL);

CREATE INDEX knowledge_shadow_created ON knowledge_shadow_comparisons(created);

CREATE TABLE knowledge_generations(
      generation_id TEXT PRIMARY KEY, curator_version TEXT NOT NULL,
      status TEXT NOT NULL, source_policy TEXT NOT NULL, config_hash TEXT NOT NULL,
      created DOUBLE PRECISION NOT NULL, activated DOUBLE PRECISION, retired DOUBLE PRECISION);

CREATE TABLE knowledge_generation_documents(
      generation_id TEXT NOT NULL, document_id TEXT NOT NULL, created DOUBLE PRECISION NOT NULL,
      PRIMARY KEY(generation_id,document_id));

CREATE INDEX knowledge_generation_documents_document
      ON knowledge_generation_documents(document_id);

CREATE TABLE knowledge_generation_state(
      singleton INTEGER PRIMARY KEY CHECK(singleton=1), active_generation_id TEXT);

CREATE TABLE knowledge_temporal_schema(
      singleton INTEGER PRIMARY KEY CHECK(singleton=1), schema_version INTEGER NOT NULL);

CREATE TABLE knowledge_temporal_assertions(
      assertion_id TEXT PRIMARY KEY, document_id TEXT NOT NULL, revision_id TEXT NOT NULL,
      project TEXT NOT NULL, subject TEXT NOT NULL, subject_key TEXT NOT NULL,
      predicate TEXT NOT NULL, predicate_key TEXT NOT NULL, actor TEXT,
      actor_key TEXT NOT NULL, qualifiers_json TEXT NOT NULL, value_json TEXT NOT NULL,
      event_at TEXT, event_start_utc DOUBLE PRECISION, event_end_utc DOUBLE PRECISION,
      event_precision TEXT, event_timezone TEXT, event_basis TEXT,
      valid_from TEXT, valid_from_utc DOUBLE PRECISION, valid_to TEXT, valid_to_utc DOUBLE PRECISION,
      valid_to_status TEXT NOT NULL, valid_precision TEXT,
      valid_timezone TEXT, valid_basis TEXT,
      recorded_at DOUBLE PRECISION NOT NULL, schema_version INTEGER NOT NULL);

CREATE INDEX knowledge_temporal_lookup ON knowledge_temporal_assertions(
      project,subject_key,predicate_key,actor_key,document_id);

CREATE INDEX knowledge_temporal_revision ON knowledge_temporal_assertions(revision_id);

CREATE TABLE knowledge_temporal_evidence(
      assertion_id TEXT NOT NULL, source_memory_id TEXT NOT NULL,
      PRIMARY KEY(assertion_id,source_memory_id));

CREATE INDEX knowledge_temporal_evidence_source
      ON knowledge_temporal_evidence(source_memory_id);

CREATE TABLE knowledge_temporal_relations(
      new_assertion_id TEXT NOT NULL, old_assertion_id TEXT NOT NULL,
      relation TEXT NOT NULL, reviewed INTEGER NOT NULL, recorded_at DOUBLE PRECISION NOT NULL,
      PRIMARY KEY(new_assertion_id,old_assertion_id,relation));

CREATE INDEX knowledge_temporal_relations_old
      ON knowledge_temporal_relations(old_assertion_id,relation,reviewed);

CREATE TABLE codex_backfill_runs(
          id TEXT PRIMARY KEY, manifest_hash TEXT NOT NULL, status TEXT NOT NULL,
          created DOUBLE PRECISION NOT NULL, updated DOUBLE PRECISION NOT NULL, counters TEXT NOT NULL);

CREATE TABLE codex_backfill_sessions(
          run_id TEXT NOT NULL, session TEXT NOT NULL, path TEXT NOT NULL,
          device BIGINT NOT NULL, inode BIGINT NOT NULL, source_size BIGINT NOT NULL,
          source_mtime_ns BIGINT NOT NULL, "offset" BIGINT NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'pending', counters TEXT NOT NULL DEFAULT '{}',
          error TEXT, PRIMARY KEY(run_id,session));

CREATE TABLE codex_backfill_events(
          session TEXT NOT NULL, capture_id TEXT NOT NULL, event_id TEXT NOT NULL,
          source_created DOUBLE PRECISION NOT NULL, imported_at DOUBLE PRECISION NOT NULL,
          PRIMARY KEY(session,capture_id));

CREATE TABLE curation_episode_jobs(
          id TEXT PRIMARY KEY, generation_id TEXT NOT NULL, episode_id TEXT NOT NULL,
          project TEXT NOT NULL, session TEXT NOT NULL, turn TEXT NOT NULL,
          source_ids TEXT NOT NULL, source_hash TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'pending', stage TEXT NOT NULL DEFAULT 'curate',
          progress TEXT NOT NULL DEFAULT '{}', attempts INTEGER NOT NULL DEFAULT 0,
          next_attempt DOUBLE PRECISION NOT NULL DEFAULT 0, created DOUBLE PRECISION NOT NULL, updated DOUBLE PRECISION NOT NULL,
          error TEXT, model TEXT, version TEXT NOT NULL, disposition TEXT,
          UNIQUE(generation_id,project,session,turn));

CREATE INDEX curation_episode_jobs_queue
          ON curation_episode_jobs(generation_id,status,next_attempt,created);

CREATE TABLE curation_episode_receipts(
          job_id TEXT NOT NULL, event_id TEXT NOT NULL, reason TEXT NOT NULL,
          created DOUBLE PRECISION NOT NULL, PRIMARY KEY(job_id,event_id,reason));

CREATE TABLE episode_candidates(
          candidate_id TEXT PRIMARY KEY, job_id TEXT NOT NULL, generation_id TEXT NOT NULL,
          candidate_key TEXT NOT NULL, candidate_json TEXT NOT NULL,
          resolution_json TEXT NOT NULL, status TEXT NOT NULL,
          document_id TEXT, created DOUBLE PRECISION NOT NULL,
          UNIQUE(job_id,candidate_key));

CREATE TABLE episode_candidate_history(
          candidate_id TEXT PRIMARY KEY,job_id TEXT NOT NULL,generation_id TEXT NOT NULL,
          candidate_key TEXT NOT NULL,candidate_json TEXT NOT NULL,resolution_json TEXT NOT NULL,
          status TEXT NOT NULL,document_id TEXT,created DOUBLE PRECISION NOT NULL,superseded_at DOUBLE PRECISION NOT NULL);

CREATE TABLE enterprise_schema(version INTEGER PRIMARY KEY, applied DOUBLE PRECISION NOT NULL);

CREATE TABLE enterprise_organizations(id TEXT PRIMARY KEY);

CREATE TABLE enterprise_principals(
              tenant TEXT NOT NULL, id TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1,
              settings_admin INTEGER NOT NULL DEFAULT 0,
              PRIMARY KEY(tenant,id), FOREIGN KEY(tenant) REFERENCES enterprise_organizations(id));

CREATE TABLE enterprise_projects(
              tenant TEXT NOT NULL, id TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1,
              PRIMARY KEY(tenant,id), FOREIGN KEY(tenant) REFERENCES enterprise_organizations(id));

CREATE TABLE enterprise_memberships(
              tenant TEXT NOT NULL, project TEXT NOT NULL, principal TEXT NOT NULL,
              active INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(tenant,project,principal),
              FOREIGN KEY(tenant,project) REFERENCES enterprise_projects(tenant,id),
              FOREIGN KEY(tenant,principal) REFERENCES enterprise_principals(tenant,id));

CREATE TABLE enterprise_credentials(
              digest TEXT PRIMARY KEY, tenant TEXT NOT NULL, principal TEXT NOT NULL,
              acting_for TEXT, enrollment TEXT NOT NULL, actions TEXT NOT NULL,
              active INTEGER NOT NULL DEFAULT 1, created DOUBLE PRECISION NOT NULL,
              FOREIGN KEY(tenant,principal) REFERENCES enterprise_principals(tenant,id),
              FOREIGN KEY(tenant,acting_for) REFERENCES enterprise_principals(tenant,id));

CREATE TABLE enterprise_delegations(
              tenant TEXT NOT NULL, principal TEXT NOT NULL, acting_for TEXT NOT NULL,
              actions TEXT NOT NULL, projects TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1,
              policy_version INTEGER NOT NULL DEFAULT 1,
              PRIMARY KEY(tenant,principal,acting_for),
              FOREIGN KEY(tenant,principal) REFERENCES enterprise_principals(tenant,id),
              FOREIGN KEY(tenant,acting_for) REFERENCES enterprise_principals(tenant,id));

CREATE TABLE enterprise_sources(
              id TEXT PRIMARY KEY, tenant TEXT NOT NULL, owner TEXT NOT NULL,
              external_project TEXT NOT NULL, internal_project TEXT NOT NULL,
              external_id TEXT NOT NULL, enrollment TEXT NOT NULL, payload_hash TEXT NOT NULL,
              visibility TEXT NOT NULL, raw_visibility TEXT NOT NULL DEFAULT 'private',
              active INTEGER NOT NULL DEFAULT 1, policy_version INTEGER NOT NULL DEFAULT 1,
              source_version INTEGER NOT NULL DEFAULT 1, occurred_at TEXT NOT NULL,
              created DOUBLE PRECISION NOT NULL,
              occurred_precision TEXT NOT NULL DEFAULT 'unknown',
              occurred_timezone TEXT,
              UNIQUE(tenant,enrollment,external_id),
              FOREIGN KEY(tenant,owner) REFERENCES enterprise_principals(tenant,id));

CREATE INDEX enterprise_source_scope ON enterprise_sources(internal_project,active);

CREATE TABLE enterprise_documents(
              id TEXT PRIMARY KEY, tenant TEXT NOT NULL, internal_project TEXT NOT NULL,
              revision TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1,
              policy_version INTEGER NOT NULL DEFAULT 1, created DOUBLE PRECISION NOT NULL,
              blocked_reason TEXT NOT NULL DEFAULT '');

CREATE TABLE enterprise_dependencies(
              document_id TEXT NOT NULL, source_id TEXT NOT NULL,
              PRIMARY KEY(document_id,source_id),
              FOREIGN KEY(document_id) REFERENCES enterprise_documents(id) ON DELETE CASCADE,
              FOREIGN KEY(source_id) REFERENCES enterprise_sources(id));

CREATE TABLE enterprise_model_inputs(
              job_id TEXT NOT NULL, related_document_id TEXT NOT NULL,
              PRIMARY KEY(job_id,related_document_id));

CREATE TABLE enterprise_receipts(
              id TEXT PRIMARY KEY, tenant TEXT NOT NULL, principal TEXT NOT NULL,
              enrollment TEXT NOT NULL, session TEXT NOT NULL, epoch TEXT NOT NULL,
              document_id TEXT NOT NULL, revision TEXT NOT NULL,
              status TEXT NOT NULL, serialized_chars INTEGER NOT NULL, created DOUBLE PRECISION NOT NULL);

CREATE TABLE enterprise_lifecycle(
              key TEXT PRIMARY KEY, tenant TEXT NOT NULL, actor TEXT NOT NULL,
              target_id TEXT NOT NULL, operation TEXT NOT NULL,
              result TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);

CREATE TABLE enterprise_audit(
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant TEXT NOT NULL, actor TEXT NOT NULL,
              operation TEXT NOT NULL, disposition TEXT NOT NULL,
              target_id TEXT, request_id TEXT, policy_version INTEGER,
              created DOUBLE PRECISION NOT NULL);

CREATE TABLE enterprise_deletion_journal(
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant TEXT NOT NULL, source_id TEXT NOT NULL,
              operation TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);

CREATE TABLE backend_connections(
          id TEXT PRIMARY KEY,tenant TEXT NOT NULL,enrollment TEXT NOT NULL,owner TEXT NOT NULL,
          namespace TEXT NOT NULL,project TEXT NOT NULL,source_types TEXT NOT NULL,
          visibility TEXT NOT NULL,reader_ids TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,
          policy_version INTEGER NOT NULL DEFAULT 1,permission_observed DOUBLE PRECISION NOT NULL,
          freshness_seconds DOUBLE PRECISION NOT NULL,capabilities TEXT NOT NULL);

CREATE TABLE backend_source_heads(
          connection TEXT NOT NULL,external_id TEXT NOT NULL,revision TEXT NOT NULL,
          source_id TEXT NOT NULL,PRIMARY KEY(connection,external_id));

CREATE TABLE backend_source_revisions(
          source_id TEXT PRIMARY KEY,connection TEXT NOT NULL,external_id TEXT NOT NULL,
          revision TEXT NOT NULL,digest TEXT NOT NULL,payload TEXT NOT NULL,received DOUBLE PRECISION NOT NULL,
          disposition TEXT NOT NULL,policy_version INTEGER NOT NULL,
          UNIQUE(connection,external_id,revision));

CREATE TABLE backend_parts(
          connection TEXT NOT NULL,external_id TEXT NOT NULL,revision TEXT NOT NULL,
          digest TEXT NOT NULL,part_index INTEGER NOT NULL,part_count INTEGER NOT NULL,
          data BYTEA NOT NULL,created DOUBLE PRECISION NOT NULL,
          PRIMARY KEY(connection,external_id,revision,part_index));

CREATE TABLE backend_ingest_receipts(
          connection TEXT NOT NULL,external_id TEXT NOT NULL,revision TEXT NOT NULL,digest TEXT NOT NULL,
          disposition TEXT NOT NULL,source_id TEXT NOT NULL,part_count INTEGER NOT NULL,created DOUBLE PRECISION NOT NULL,
          PRIMARY KEY(connection,external_id,revision));

CREATE TABLE backend_part_hashes(
          connection TEXT NOT NULL,external_id TEXT NOT NULL,revision TEXT NOT NULL,
          part_index INTEGER NOT NULL,sha256 TEXT NOT NULL,
          PRIMARY KEY(connection,external_id,revision,part_index));

CREATE TABLE backend_capture_gaps(
          source_id TEXT PRIMARY KEY,connection TEXT NOT NULL,reason TEXT NOT NULL,created DOUBLE PRECISION NOT NULL);

CREATE TABLE backend_source_links(
          source_id TEXT NOT NULL,origin_source_id TEXT NOT NULL,kind TEXT NOT NULL,
          PRIMARY KEY(source_id,origin_source_id,kind));

CREATE TABLE backend_native_artifacts(
          document_id TEXT PRIMARY KEY,source_id TEXT NOT NULL,artifact_kind TEXT NOT NULL,source_url TEXT NOT NULL);

CREATE TABLE backend_native_spans(
          document_id TEXT PRIMARY KEY,source_id TEXT NOT NULL,start INTEGER NOT NULL,
          "end" INTEGER NOT NULL,heading TEXT NOT NULL);

CREATE TABLE backend_releases(
        id TEXT PRIMARY KEY,document_id TEXT NOT NULL,original_document TEXT NOT NULL,
        original_revision TEXT NOT NULL,tenant TEXT NOT NULL,actor TEXT NOT NULL,
        readers TEXT NOT NULL,dependencies TEXT NOT NULL,created DOUBLE PRECISION NOT NULL);

CREATE TABLE backend_observers(
          id TEXT PRIMARY KEY,tenant TEXT NOT NULL,connection TEXT NOT NULL,conversation TEXT NOT NULL,
          internal_project TEXT NOT NULL,generation TEXT NOT NULL,permission_hash TEXT NOT NULL,
          model TEXT NOT NULL,prompt_version TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ready',
          provider_session TEXT,pending_session TEXT,observer_epoch INTEGER NOT NULL DEFAULT 0,
          source_epoch INTEGER NOT NULL DEFAULT 0,checkpoint TEXT NOT NULL DEFAULT '{}',
          context_chars INTEGER NOT NULL DEFAULT 0,updated DOUBLE PRECISION NOT NULL);

CREATE TABLE backend_jobs(
          id TEXT PRIMARY KEY,episode_job TEXT NOT NULL,observer_id TEXT NOT NULL,source_hash TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'pending',fence TEXT,lease_until DOUBLE PRECISION NOT NULL DEFAULT 0,
          attempts INTEGER NOT NULL DEFAULT 0,recovery TEXT NOT NULL DEFAULT '',
          dispatch_attempt TEXT,pending_result TEXT,last_error TEXT,created DOUBLE PRECISION NOT NULL,updated DOUBLE PRECISION NOT NULL);

CREATE TABLE backend_observer_dependencies(
          observer_id TEXT NOT NULL,source_id TEXT NOT NULL,policy_version INTEGER NOT NULL,
          PRIMARY KEY(observer_id,source_id));

CREATE TABLE backend_processing_dependencies(
          episode_job TEXT NOT NULL,source_id TEXT NOT NULL,policy_version INTEGER NOT NULL,
          PRIMARY KEY(episode_job,source_id));

CREATE TABLE backend_worker_receipts(
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,job_id TEXT NOT NULL,attempt_id TEXT,purpose TEXT,
          status TEXT NOT NULL,usage TEXT,elapsed DOUBLE PRECISION,created DOUBLE PRECISION NOT NULL, is_live INTEGER NOT NULL DEFAULT 0);

CREATE TABLE backend_connectors(
        id TEXT PRIMARY KEY,connection TEXT NOT NULL,adapter TEXT NOT NULL,path TEXT NOT NULL,
        policy_file TEXT,max_visibility TEXT NOT NULL,max_readers TEXT NOT NULL,
        cursor INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'enrolled',updated DOUBLE PRECISION NOT NULL);

CREATE TABLE backend_connector_items(
        connector TEXT NOT NULL,external_id TEXT NOT NULL,content_hash TEXT NOT NULL,
        revision INTEGER NOT NULL,source_id TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,
        PRIMARY KEY(connector,external_id));

CREATE TABLE context_state(
            session TEXT PRIMARY KEY, epoch INTEGER NOT NULL DEFAULT 0,
            boundary_id TEXT, latest_sequence INTEGER NOT NULL DEFAULT -1,
            observed_cursor INTEGER, observed_turn TEXT,
            uncertain_since DOUBLE PRECISION NOT NULL DEFAULT 0,
            gap_reason TEXT,
            boundary_support TEXT NOT NULL DEFAULT 'unknown',
            continuity_status TEXT NOT NULL DEFAULT 'unknown',
            coverage_status TEXT NOT NULL DEFAULT 'unknown', updated DOUBLE PRECISION NOT NULL);

CREATE TABLE context_boundaries(
            session TEXT NOT NULL, boundary_id TEXT NOT NULL, kind TEXT NOT NULL,
            observed_at TEXT NOT NULL, source_adapter TEXT NOT NULL,
            sequence INTEGER NOT NULL, source_cursor INTEGER,
            applied INTEGER NOT NULL, created DOUBLE PRECISION NOT NULL,
            PRIMARY KEY(session,boundary_id));

CREATE TABLE context_retained(
            session TEXT NOT NULL, epoch INTEGER NOT NULL, document_id TEXT NOT NULL,
            revision_id TEXT NOT NULL, source TEXT NOT NULL, created DOUBLE PRECISION NOT NULL,
            PRIMARY KEY(session,epoch,document_id,revision_id));

CREATE TABLE context_receipts(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session TEXT NOT NULL, epoch INTEGER NOT NULL,
            request_key TEXT NOT NULL, document_id TEXT NOT NULL,
            revision_id TEXT NOT NULL, generation_id TEXT NOT NULL,
            claim_key TEXT NOT NULL, answer_fingerprint TEXT NOT NULL,
            layer TEXT NOT NULL, channel TEXT NOT NULL,
            final_serialized_characters INTEGER NOT NULL,
            decision TEXT NOT NULL, status TEXT NOT NULL, created DOUBLE PRECISION NOT NULL,
            UNIQUE(session,epoch,request_key,claim_key,answer_fingerprint,layer));

CREATE INDEX context_receipts_novelty
            ON context_receipts(session,epoch,claim_key,answer_fingerprint,layer,status);

CREATE INDEX knowledge_fts_gin ON knowledge_fts USING GIN(to_tsvector('simple',body));

CREATE INDEX memory_fts_gin ON memory_fts USING GIN(to_tsvector('simple',body));

INSERT INTO enterprise_schema(version,applied) VALUES(1,extract(epoch from clock_timestamp())),(2,extract(epoch from clock_timestamp())),(3,extract(epoch from clock_timestamp())),(4,extract(epoch from clock_timestamp()));

INSERT INTO knowledge_index_state VALUES(1,2);

INSERT INTO knowledge_temporal_schema VALUES(1,1);
