-- Rebuildable search authorization projection. Full source provenance is retained.
-- Trigger maintenance is transactional, including writes from older installations.
LOCK TABLE enterprise_sources,backend_source_revisions,cloud_source_acl,enterprise_dependencies
    IN SHARE ROW EXCLUSIVE MODE;

CREATE INDEX enterprise_dependencies_source_document ON enterprise_dependencies(source_id,document_id);
CREATE TABLE search_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition JSONB NOT NULL UNIQUE
);
INSERT INTO search_policies(id,definition) VALUES(0,'{"missing":true}');
CREATE TABLE search_source_policies (
    source_id TEXT PRIMARY KEY,
    policy_id BIGINT NOT NULL REFERENCES search_policies(id)
);
CREATE TABLE search_document_policies (
    document_id TEXT NOT NULL,
    policy_id BIGINT NOT NULL REFERENCES search_policies(id),
    dependency_count BIGINT NOT NULL,
    PRIMARY KEY(document_id,policy_id)
);
CREATE INDEX search_document_policies_policy ON search_document_policies(policy_id,document_id);
-- Signed deltas exist only inside a maintenance statement; validate before return.
CREATE INDEX search_document_policies_nonpositive ON search_document_policies(dependency_count)
    WHERE dependency_count<=0;

CREATE VIEW search_source_policy_definitions AS
SELECT s.id AS source_id,jsonb_build_object(
    'tenant',s.tenant,'owner',s.owner,'project',s.external_project,
    'visibility',s.visibility,'active',s.active,
    'has_revision',r.source_id IS NOT NULL,'connection',r.connection,
    'has_acl',a.source_id IS NOT NULL,'acl_state',a.state,'acl_until',a.valid_until
) AS definition
FROM enterprise_sources s
LEFT JOIN backend_source_revisions r ON r.source_id=s.id
LEFT JOIN cloud_source_acl a ON a.source_id=s.id;

CREATE FUNCTION search_policy_projection_lock() RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    -- Serialize projection writers per tenant schema, never search readers.
    PERFORM pg_advisory_xact_lock(hashtextextended(current_schema()||':search-policy-projection',0));
END $$;

CREATE FUNCTION search_policy_validate_counts() RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS(SELECT 1 FROM search_document_policies WHERE dependency_count<0) THEN
        RAISE EXCEPTION 'search_policy_negative_dependency_count';
    END IF;
    DELETE FROM search_document_policies WHERE dependency_count=0;
END $$;

CREATE FUNCTION search_refresh_source_policies(ids TEXT[]) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    PERFORM search_policy_projection_lock();
    IF ids IS NULL THEN
        SELECT array_agg(source_id) INTO ids FROM (
            SELECT id source_id FROM enterprise_sources UNION SELECT source_id FROM search_source_policies
        ) all_sources;
    END IF;
    IF coalesce(cardinality(ids),0)=0 THEN RETURN; END IF;
    INSERT INTO search_policies(definition)
        SELECT DISTINCT definition FROM search_source_policy_definitions WHERE source_id=ANY(ids)
        ON CONFLICT(definition) DO NOTHING;
    WITH changes AS MATERIALIZED (
        SELECT i.source_id,coalesce(old.policy_id,0) old_policy,coalesce(p.id,0) new_policy
        FROM unnest(ids) i(source_id)
        LEFT JOIN search_source_policies old USING(source_id)
        LEFT JOIN search_source_policy_definitions fresh USING(source_id)
        LEFT JOIN search_policies p ON p.definition=fresh.definition
        WHERE coalesce(old.policy_id,0)!=coalesce(p.id,0)
    ), deltas AS (
        SELECT x.document_id,c.old_policy policy_id,-count(*) amount
        FROM changes c JOIN enterprise_dependencies x USING(source_id) GROUP BY x.document_id,c.old_policy
        UNION ALL
        SELECT x.document_id,c.new_policy policy_id,count(*) amount
        FROM changes c JOIN enterprise_dependencies x USING(source_id) GROUP BY x.document_id,c.new_policy
    )
    INSERT INTO search_document_policies(document_id,policy_id,dependency_count)
        SELECT document_id,policy_id,sum(amount)::bigint FROM deltas GROUP BY document_id,policy_id
        HAVING sum(amount)!=0
        ON CONFLICT(document_id,policy_id) DO UPDATE
            SET dependency_count=search_document_policies.dependency_count+excluded.dependency_count;
    INSERT INTO search_source_policies(source_id,policy_id)
        SELECT i.source_id,coalesce(p.id,0) FROM unnest(ids) i(source_id)
        LEFT JOIN search_source_policy_definitions fresh USING(source_id)
        LEFT JOIN search_policies p ON p.definition=fresh.definition
        ON CONFLICT(source_id) DO UPDATE SET policy_id=excluded.policy_id;
    PERFORM search_policy_validate_counts();
END $$;

CREATE FUNCTION search_policy_source_changed() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE ids TEXT[]; relation_sql TEXT;
BEGIN
    IF TG_OP='TRUNCATE' THEN
        PERFORM search_refresh_source_policies(NULL); RETURN NULL;
    END IF;
    relation_sql=CASE TG_OP
        WHEN 'INSERT' THEN 'SELECT '||quote_ident(TG_ARGV[0])||' source_id FROM new_rows'
        WHEN 'DELETE' THEN 'SELECT '||quote_ident(TG_ARGV[0])||' source_id FROM old_rows'
        ELSE 'SELECT '||quote_ident(TG_ARGV[0])||' source_id FROM new_rows UNION SELECT '||quote_ident(TG_ARGV[0])||' source_id FROM old_rows'
    END;
    EXECUTE 'SELECT array_agg(DISTINCT source_id) FROM ('||relation_sql||') changed' INTO ids;
    -- Empty transition tables are not a request to rebuild the whole corpus.
    IF ids IS NOT NULL THEN PERFORM search_refresh_source_policies(ids); END IF;
    RETURN NULL;
END $$;

CREATE FUNCTION search_policy_dependencies_changed() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE relation_sql TEXT;
BEGIN
    PERFORM search_policy_projection_lock();
    IF TG_OP='TRUNCATE' THEN DELETE FROM search_document_policies; RETURN NULL; END IF;
    relation_sql=CASE TG_OP
        WHEN 'INSERT' THEN 'SELECT document_id,source_id,1 amount FROM new_rows'
        WHEN 'DELETE' THEN 'SELECT document_id,source_id,-1 amount FROM old_rows'
        ELSE 'SELECT document_id,source_id,1 amount FROM new_rows UNION ALL SELECT document_id,source_id,-1 amount FROM old_rows'
    END;
    EXECUTE 'INSERT INTO search_document_policies(document_id,policy_id,dependency_count)
        SELECT d.document_id,coalesce(p.policy_id,0),sum(d.amount)::bigint
        FROM ('||relation_sql||') d LEFT JOIN search_source_policies p USING(source_id)
        GROUP BY d.document_id,coalesce(p.policy_id,0) HAVING sum(d.amount)!=0
        ON CONFLICT(document_id,policy_id) DO UPDATE
            SET dependency_count=search_document_policies.dependency_count+excluded.dependency_count';
    PERFORM search_policy_validate_counts();
    RETURN NULL;
END $$;

-- Explicit maintenance/restore operation, never called by serving constructors.
CREATE FUNCTION search_rebuild_permissions() RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    LOCK TABLE enterprise_sources,backend_source_revisions,cloud_source_acl,enterprise_dependencies
        IN SHARE ROW EXCLUSIVE MODE;
    PERFORM search_policy_projection_lock();
    INSERT INTO search_policies(definition)
        SELECT DISTINCT definition FROM search_source_policy_definitions ON CONFLICT DO NOTHING;
    DELETE FROM search_document_policies;
    DELETE FROM search_source_policies;
    INSERT INTO search_source_policies
        SELECT s.source_id,p.id FROM search_source_policy_definitions s JOIN search_policies p USING(definition);
    INSERT INTO search_document_policies
        SELECT x.document_id,coalesce(p.policy_id,0),count(*)
        FROM enterprise_dependencies x LEFT JOIN search_source_policies p USING(source_id)
        GROUP BY x.document_id,coalesce(p.policy_id,0);
END $$;
SELECT search_rebuild_permissions();

CREATE TRIGGER search_source_insert AFTER INSERT ON enterprise_sources
    REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('id');
CREATE TRIGGER search_source_update AFTER UPDATE ON enterprise_sources
    REFERENCING NEW TABLE AS new_rows OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('id');
CREATE TRIGGER search_source_delete AFTER DELETE ON enterprise_sources
    REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('id');
CREATE TRIGGER search_source_truncate AFTER TRUNCATE ON enterprise_sources
    FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('id');
CREATE TRIGGER search_revision_insert AFTER INSERT ON backend_source_revisions
    REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('source_id');
CREATE TRIGGER search_revision_update AFTER UPDATE ON backend_source_revisions
    REFERENCING NEW TABLE AS new_rows OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('source_id');
CREATE TRIGGER search_revision_delete AFTER DELETE ON backend_source_revisions
    REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('source_id');
CREATE TRIGGER search_revision_truncate AFTER TRUNCATE ON backend_source_revisions
    FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('source_id');
CREATE TRIGGER search_acl_insert AFTER INSERT ON cloud_source_acl
    REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('source_id');
CREATE TRIGGER search_acl_update AFTER UPDATE ON cloud_source_acl
    REFERENCING NEW TABLE AS new_rows OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('source_id');
CREATE TRIGGER search_acl_delete AFTER DELETE ON cloud_source_acl
    REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('source_id');
CREATE TRIGGER search_acl_truncate AFTER TRUNCATE ON cloud_source_acl
    FOR EACH STATEMENT EXECUTE FUNCTION search_policy_source_changed('source_id');
CREATE TRIGGER search_dependency_insert AFTER INSERT ON enterprise_dependencies
    REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_dependencies_changed();
CREATE TRIGGER search_dependency_update AFTER UPDATE ON enterprise_dependencies
    REFERENCING NEW TABLE AS new_rows OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_dependencies_changed();
CREATE TRIGGER search_dependency_delete AFTER DELETE ON enterprise_dependencies
    REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION search_policy_dependencies_changed();
CREATE TRIGGER search_dependency_truncate AFTER TRUNCATE ON enterprise_dependencies
    FOR EACH STATEMENT EXECUTE FUNCTION search_policy_dependencies_changed();
